name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v node &> /dev/null
            then
                echo "Node.js tidak ditemukan, menginstal Node.js..."
                curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
                sudo apt-get install -y nodejs
            fi

            if ! command -v npm &> /dev/null
            then
                echo "npm tidak ditemukan, menginstal npm..."
                sudo apt-get install -y npm
            fi

            if ! command -v pm2 &> /dev/null
            then
                echo "pm2 tidak ditemukan, menginstal pm2..."
                sudo npm install -g pm2
            fi

            cd ~/forumapiserver
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forum-api
